plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.adk:google-adk:1.11.0'
    implementation 'com.google.adk:google-adk-dev:1.11.0'

    // core LangChain4j library and OpenAI compatible model
    implementation 'com.google.adk:google-adk-langchain4j:1.11.0'
    implementation 'dev.langchain4j:langchain4j-core:1.21.0'
    implementation 'dev.langchain4j:langchain4j-open-ai:1.21.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'de.qaware.agentic.AgentCliRunner'
}

tasks.register('runAdkWebServer', JavaExec) {
    dependsOn classes
    group = 'application'
    description = 'Runs the ADK web server.'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.google.adk.web.AdkWebServer'
    args '--adk.agents.source-dir=build/classes/java', '--server.port=8000', '--reload'
}
